// 
// Generated by @himenon/openapi-typescript-code-generator v0.10.1
// 
// OpenApi : 3.0.0
// 
// License  : MIT
// 


export namespace Schemas {
    export interface Pet {
        id: number;
        name: string;
        tag?: string;
    }
    export type Pets = Schemas.Pet[];
    export interface Error {
        code: number;
        message: string;
    }
}
